### ISSUE TITLE
Absturz Tab Belegungsplan

### ISSUE THREAD

**Issue by Lucas170799** [HTWDD/HTWDresden-Android#16]
Workflow:
- App starten
- in Tab Belegungsplan wechseln

Ist Zustand:
Die App stürzt ab. (Habe keine Studiengruppe hinterlegt, da meine im Moment noch nicht verfügbar ist.)

LG Lucas

**Comment by FestPlatin** [comment]
Hallo Lucas,
vielen Dank für dein Rückmeldung. Leider wird die App seit ungefähr einen halben Jahr nicht mehr von mir gepflegt, dies hat jetzt offiziell die HTW Dresden übernommen. Hier kannst du nur bei der HTW einmal anfragen :/

LG,
Kay
